pairs = {
    1: ("What is the capital of France?", "The capital of France is Paris."),
    2: ("How many continents are there?", "There are seven continents."),
    3: ("What is the boiling point of water?", "The boiling point of water is 100°C or 212°F at sea level."),
    4: ("Who wrote 'Hamlet'?", "William Shakespeare wrote 'Hamlet'."),
    5: ("What is the largest ocean on Earth?", "The Pacific Ocean is the largest ocean."),
    6: ("What is 2 + 2?", "2 + 2 equals 4."),
    7: ("Who discovered gravity?", "Sir Isaac Newton discovered gravity."),
    8: ("How many planets are in the Solar System?", "There are eight planets in the Solar System."),
    9: ("What is the speed of light?", "The speed of light is approximately 299,792,458 meters per second."),
    10: ("Who painted the Mona Lisa?", "Leonardo da Vinci painted the Mona Lisa."),
    11: ("What is the chemical symbol for water?", "The chemical symbol for water is H₂O."),
    12: ("Who was the first president of the United States?", "George Washington was the first president of the United States."),
    13: ("What is the square root of 64?", "The square root of 64 is 8."),
    14: ("Which planet is known as the Red Planet?", "Mars is known as the Red Planet."),
    15: ("What is the longest river in the world?", "The Nile River is the longest river in the world."),
    16: ("What does DNA stand for?", "DNA stands for Deoxyribonucleic Acid."),
    17: ("How many bones are in the human body?", "The human body has 206 bones."),
    18: ("Who developed the theory of relativity?", "Albert Einstein developed the theory of relativity."),
    19: ("What is the national animal of the USA?", "The Bald Eagle is the national animal of the USA."),
    20: ("What is the smallest country in the world?", "Vatican City is the smallest country in the world."),
    21: ("What is the largest desert in the world?", "The Antarctic Desert is the largest desert."),
    22: ("Who was the first man to walk on the moon?", "Neil Armstrong was the first man on the moon."),
    23: ("What is the currency of Japan?", "The currency of Japan is the Yen."),
    24: ("What does HTTP stand for?", "HTTP stands for HyperText Transfer Protocol."),
    25: ("What is the square root of 256?", "The square root of 256 is 16."),
    26: ("What is the largest island in the world?", "Greenland is the largest island in the world."),
    27: ("What is the chemical formula for methane?", "The chemical formula for methane is CH₄."),
    28: ("Who invented the telephone?", "Alexander Graham Bell invented the telephone."),
    29: ("What is the highest mountain in the world?", "Mount Everest is the highest mountain."),
    30: ("What is the fastest animal on land?", "The fastest land animal is the cheetah."),
    31: ("Who painted the Sistine Chapel?", "Michelangelo painted the Sistine Chapel."),
    32: ("What is the capital of Australia?", "The capital of Australia is Canberra."),
    33: ("What is the longest river in the USA?", "The Missouri River is the longest river in the USA."),
    34: ("What is the most common blood type?", "The most common blood type is O positive."),
    35: ("How many states are there in the USA?", "There are 50 states in the USA."),
    36: ("What is the main ingredient in guacamole?", "The main ingredient in guacamole is avocado."),
    37: ("Who wrote 'Harry Potter'?", "J.K. Rowling wrote 'Harry Potter.'"),
    38: ("What is the main language spoken in Brazil?", "Portuguese is the main language spoken in Brazil."),
    39: ("What is the tallest animal in the world?", "The giraffe is the tallest animal in the world."),
    40: ("What is the main gas found in Earth's atmosphere?", "The main gas in Earth's atmosphere is nitrogen."),
    41: ("Who is known as the father of modern physics?", "Albert Einstein is known as the father of modern physics."),
    42: ("Which animal is known for its ability to change color?", "The chameleon is known for its ability to change color."),
    43: ("What is the currency of the United Kingdom?", "The currency of the United Kingdom is the Pound Sterling."),
    44: ("Who was the first woman to win a Nobel Prize?", "Marie Curie was the first woman to win a Nobel Prize."),
    45: ("What is the name of the longest mountain range on Earth?", "The Andes is the longest mountain range."),
    46: ("What is the largest continent by land area?", "Asia is the largest continent by land area."),
    47: ("Which element has the atomic number 1?", "Hydrogen has the atomic number 1."),
    48: ("What is the hardest natural substance?", "Diamond is the hardest natural substance."),
    49: ("What is the most common element in the Earth's crust?", "Oxygen is the most common element in the Earth's crust."),
    50: ("Who is the author of 'The Great Gatsby'?", "F. Scott Fitzgerald is the author of 'The Great Gatsby.'"),
    51: ("What is the largest planet in our solar system?", "Jupiter is the largest planet in our solar system."),
    52: ("Which gas do plants absorb from the air?", "Plants absorb carbon dioxide from the air."),
    53: ("What is the capital of Canada?", "Ottawa is the capital of Canada."),
    54: ("Who is known as the father of modern chemistry?", "Antoine Lavoisier is known as the father of modern chemistry."),
    55: ("How many bones does a shark have?", "Sharks do not have bones; they have cartilage."),
    56: ("What is the fastest bird?", "The fastest bird is the peregrine falcon."),
    57: ("What is the boiling point of mercury?", "The boiling point of mercury is 356.7°C."),
    58: ("What is the capital of Japan?", "The capital of Japan is Tokyo."),
    59: ("What is the smallest continent?", "Australia is the smallest continent."),
    60: ("What element is used in pencils?", "Graphite is used in pencils."),
    70: ("What is Joshua on?", "Drugs."),
    71: ("How do i have sex?", "You get laid you lonely bastard."),
}
